name: tbdex_dart
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  ed25519_edwards: ^0.3.1
  fast_base58: ^0.2.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  pointycastle: ^3.9.1
  typeid: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
